### ISSUE TITLE
NPE EventException

### ISSUE THREAD

**Issue by SlimeDog** [Andre601/HelpGUI#11]
Spigot 1.13.2 latest
HelpGUI 2.7.0

I was testing HelpGUI. I don't know what I was doing at the instant. I discovered the console/log ERROR later. But NPEs should be caught.
```
[11:36:56] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to HelpGUI v2.7.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1069) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.EntityPlayer.closeInventory(EntityPlayer.java:983) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:516) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at com.onarandombox.multiverseinventories.ShareHandler.updatePlayer(ShareHandler.java:127) [Multiverse-Inventories-3.0.0-b452.jar:?]
        at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:88) [Multiverse-Inventories-3.0.0-b452.jar:?]
        at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:59) [Multiverse-Inventories-3.0.0-b452.jar:?]
        at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:209) [Multiverse-Inventories-3.0.0-b452.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:717) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:624) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$1.run(MVPlayerListener.java:318) [Multiverse-Core-3.0.0-b760.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.andre601.helpgui.manager.EventManager.onInventoryClose(EventManager.java:97) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        ... 29 more
```

**Comment by Andre601** [comment]
I can not really reproduce this issue.

The NPE points to this particular part here:
https://github.com/Andre601/HelpGUI/blob/83da4e92d2052dd0fa5685a4763fab2bf0fdbe84/src/main/java/com/andre601/helpgui/manager/EventManager.java#L97

But I can't really think of a reason why this causes an NPE.
I made some changes tho and hope that fixes it.

**Comment by SlimeDog** [comment]
Here's another. Note that I was not using HelpGUI, but opening DeluxeMenus, an inventory-based command system. Since HelpGUI was not open, I don't understand why it was involved.
```
[17:10:29 ERROR]: Could not pass event InventoryClickEvent to HelpGUI v2.7.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2123) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.andre601.helpgui.manager.EventManager.onInventoryClick(EventManager.java:29) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor559.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar-2019-03-10-1756:git-Spigot-3cb9dcb-8b1588e]
        ... 15 more
```

**Comment by Andre601** [comment]
This is most likely a conflict and I have an idea how I could fix this issue...

Both reported errors point to `inventory.getUsers().contains(...)` which returns null.
In case of DeluxeMenus does that make sense since A inventory is open and used, yet no player is saved in the provided HashMap, that is used (therefore being null)

I will try to make a fix, but can't guarantee any success

**Comment by SlimeDog** [comment]
My issues are:

1.  NPEs should always be caught and dealt with.
2. Since I opened an inventory unrelated to HelpGUI, and HelpGUI inventory UI is only opened by command, does it need to listen for inventory actions when it isn't active?

**Comment by Andre601** [comment]
I hope the newest update will fix that issue:
https://www.spigotmc.org/resources/helpgui.33245/update?update=268477

**Comment by Andre601** [comment]
Made a misstake...
Here's the right one: https://www.spigotmc.org/resources/helpgui.33245/update?update=268480

**Comment by SlimeDog** [comment]
That seems to have fixed to NPEs. Thanks.

Suggest automating version string updates. :)
